services:
  backend:
    build: 
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
  
  web:
    build: ./frontend/web
    ports:
      - 5173:5173
    volumes:
      - ./frontend/web:/web
    depends_on:
      - backend
